### ISSUE TITLE
Error occurs when generate Spatial Visualization

### ISSUE THREAD

**Issue by rageworx** [rageworx/GIA-Practice-Tests#1]
Error occurs when generate Spatial Visualization
 
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 861, in callit
    func(*args)
  File "/Users/raphaelkim/Projects/GIA/GIA-Practice-Tests/main.py", line 91, in countdown_timer
    show_score()
  File "/Users/raphaelkim/Projects/GIA/GIA-Practice-Tests/main.py", line 77, in show_score
    spatial_visualisation.save_report()
  File "/Users/raphaelkim/Projects/GIA/GIA-Practice-Tests/spatial_visualisation.py", line 114, in save_report
    print_report_to_pdf(pdf, self.report)
  File "/Users/raphaelkim/Projects/GIA/GIA-Practice-Tests/spatial_visualisation.py", line 34, in print_report_to_pdf
    pdf.image(line[column], w=10, h=10, x=x_cord, y=y_cord)
  File "/usr/local/lib/python3.11/site-packages/fpdf/fpdf.py", line 150, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fpdf/fpdf.py", line 960, in image
    if not name in self.images:
           ^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'Image'
```

**Comment by rageworx** [comment]
It is must be here ...

<img width="564" alt="image" src="https://github.com/rageworx/GIA-Practice-Tests/assets/6948225/e3874ecc-890e-4670-9679-6c0354ec859c">

I don't understand why is it works on Python.

**Comment by rageworx** [comment]
I don't imagine what is image from report ? from line[column]. How it become to an image ?

Refer to FPDF, https://pyfpdf.github.io/fpdf2/Images.html.

Python is mysterious ...

**Comment by rageworx** [comment]
Fixed to using right way for python 3.11.x

<img width="580" alt="image" src="https://github.com/rageworx/GIA-Practice-Tests/assets/6948225/8e5abe5b-6e6d-4457-85d6-f325c69eea62">

as result is :

<img width="690" alt="image" src="https://github.com/rageworx/GIA-Practice-Tests/assets/6948225/90d2a634-ad9d-49d7-a160-99442a7a6af4">

**Comment by rageworx** [comment]
Still I don't understand why Python is not so plainness.

**Comment by rageworx** [comment]
It should be enhanced to write image to `/tmp` or private tmp directory .. 
But I don't know Python has some predefined paths to determine where is temporary directory.

**Comment by rageworx** [comment]
Method changed -> writes temporary PNG file in reports directory and remove it after insert to PDF.
